# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZUvNsvnFOEmULTnICspwTDIAPKJkm3d6
"""

import numpy as np
import cv2
from google.colab.patches import cv2_imshow

detector_facial = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

imagem= cv2.imread('people1.jpg')
imagem_cinza = cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY)
#print (imagem.shape, imagem_cinza.shape)
deteccoes = detector_facial.detectMultiScale(imagem_cinza)
#print(len(deteccoes))
for (x,y,l,a) in deteccoes:
  cv2.rectangle(imagem, (x,y), (x+l, y+a), (0,255,255), 2)
cv2_imshow(imagem)

imagem = cv2.imread('people1.jpg')
imagem_redirecionada = cv2.resize(imagem, (600,480))
imagem_cinza = cv2.cvtColor(imagem_redirecionada, cv2.COLOR_BGR2GRAY)
deteccoes = detector_facial.detectMultiScale(imagem_cinza)
for (x,y,l,a) in deteccoes:
  cv2.rectangle(imagem_redirecionada, (x,y), (x+l, y+a), (0,255,255), 2)
  cv2_imshow(imagem_redirecionada)